### ISSUE TITLE
✨Rule Content Linting

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.Rules.Content#2749]
Cc: @bradystroud @adamcogan @tiagov8 
  
Hi Team,

## Pain  
Recently there have been some rules that on merge have caused builds to fail. These are often due to malformed Markdown or frontmatter that have small issues like an incorrect amount of spaces. These are things that anyone could miss and as such should be part of automated checks. 

## Solution
To make rules as non-blocking as possible, I recommend adding 1-2 new actions that run per PR to validate the Markdown and its Frontmatter (yaml). 

From a quick search, here are a few already made actions that help solve this issue:

- [markdownlint](https://github.com/articulate/actions-markdownlint)
- [lint-md-fm](https://github.com/timhagn/lint-md-fm)

## Tasks
- [ ] Investigate the best actions to use lint/validate Markdown
- [ ] Investigate the best actions to use lint/validate Frontmatter
- [ ] Implement the new actions

Thanks

**Comment by JackDevAU** [comment]
Closed as https://github.com/SSWConsulting/SSW.Rules/issues/514 already address this issue.
