### ISSUE TITLE
🐛 Turn emails into PBIs - Fix broken image

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.Rules.Content#9594]
cc @adamcogan @tiagov8 @bradystroud @UlyssesMaclaren @Calinator444 
  
Hi @Calinator444 
  
https://www.ssw.com.au/rules/turn-emails-into-pbis/

**Pain**
On this rule, the first figure "Should the email be turned into a PBI" is broken
Text is truncated so all we can see are "Does this email..." or "How long will..."

Upon investigating with @tiagov8, it looks like it was broken in this PR when you converted the image to PNG - https://github.com/SSWConsulting/SSW.Rules.Content/commit/9698f428ee18eff65e1131cd103655d4a94e148c

In the previous version, you can see the correct image - https://github.com/SSWConsulting/SSW.Rules.Content/commit/b76ab4707b792a840e8c41df1e2e7401f04c6af6

**Tasks**
- [x] Please fix the image
- [x] Get it checked by Betty or Tiago
- [x] Reply done to email - Re: Do you escalate key updates and deliverables? | SSW.Rules

![Image](https://github.com/user-attachments/assets/b710992b-fedb-4d79-a0e8-a0a4973ebb1b)
**Figure: Broken Image (Live)**

![Image](https://github.com/user-attachments/assets/a0bcc5b0-cbf1-48d9-bee2-abe2e79af7cb)
**Figure: Correct Image (from previous version)**

**Comment by tiagov8** [comment]
Related 🐛 BUG: https://github.com/SSWConsulting/SSW.Rules/issues/1442
